apiVersion: batch/v1
kind: CronJob
metadata:
  name: trigger-commodities
spec:
  schedule: "*/10 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: endpoint-trigger
            image: curlimages/curl:latest
            command:
            - /bin/sh
            - -c
            - |
              ENDPOINTS="http://data-collection.default.svc.cluster.local:80/commodities/scrape-and-send/WTI \
                         http://data-collection.default.svc.cluster.local:80/commodities/scrape-and-send/BRENT \
                         http://data-collection.default.svc.cluster.local:80/commodities/scrape-and-send/NATURAL_GAS \
                         http://data-collection.default.svc.cluster.local:80/commodities/scrape-and-send/COFFEE \
                         http://data-collection.default.svc.cluster.local:80/commodities/scrape-and-send/COTTON"
              DELAY=10  # Delay of 10 seconds between each request
              
              # Loop over endpoints and hit them with a delay
              for endpoint in $ENDPOINTS; do
                echo "Hitting $endpoint"
                curl -X POST "$endpoint"
                echo "Sleeping for $DELAY seconds before hitting the next endpoint"
                sleep $DELAY
              done
          restartPolicy: OnFailure