apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: data-collection-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: data-collection
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70