apiVersion: batch/v1
kind: CronJob
metadata:
  name: trigger-stocks-north-america
spec:
  schedule: "*/10 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: endpoint-trigger
            image: curlimages/curl:latest
            command:
            - /bin/sh
            - -c
            - |
              ENDPOINTS="http://data-collection.default.svc.cluster.local:80/stocks/scrape-and-send/usa \
                         http://data-collection.default.svc.cluster.local:80/stocks/scrape-and-send/canada"
              DELAY=20
              
              # Loop over endpoints and hit them with a delay
              for endpoint in $ENDPOINTS; do
                echo "Hitting $endpoint"
                curl -X POST "$endpoint"
                echo "Sleeping for $DELAY seconds before hitting the next endpoint"
                sleep $DELAY
              done
          restartPolicy: OnFailure