apiVersion: batch/v1
kind: CronJob
metadata:
  name: trigger-bonds
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: single-endpoint-trigger
            image: curlimages/curl:latest
            command:
            - /bin/sh
            - -c
            - |
              ENDPOINT="http://data-collection.default.svc.cluster.local:80/bonds/scrape-and-send/bonds/"
              echo "Hitting $ENDPOINT"
              curl -X POST "$ENDPOINT"
          restartPolicy: OnFailure
