apiVersion: v1
kind: Service
metadata:
  name: data-collection
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 32000 # You can choose a node port between 30000-32767
  selector:
    app: data-collection

